theme: jekyll-theme-minimal
title: Busy/Free Desk Indicator
description: DeckerEgo Corp thanks you for your purchase of the Busy/Free Desk Indicator 2021 Edition. We hope it brings you years of enjoyment and use.
github_username:  deckerego
